### PR TITLE
Developer Tools

### PR DESCRIPTION
**Pull request by LeeGodSRC**
Some work (actually most of them will be in this PR) towards #122 .

### Framework Changes
- [x] Add the ability to customize the Fairy class path in the plugin (for more flexibility and so it doesn't assume you always relocated it).
- [x] Make sure Bukkit reload works in most cases.

### Developer Tools
- [x] Ability to single line `Restarter.restart(plugin)` which restarts the plugin's lifecycle. (CORE)
- [x] A source file watcher that will **hot reload** the plugin whenever it detects changes from source file (aka Build in IDE). (CORE)
- [x] Built-in one-click in-game test environment (just like run-paper but better support with hotswapping). (BUKKIT)
- [x] When triggering a **hot reload** on a bukkit plugin, it should unload the plugin completely from bukkit and load it back. (BUKKIT)
- [x] DCEVM hotswap agent should have an option to enable/disable hot reload on source file change detected. (since some hotswap changes may not necessary require a full hot reload.) (CORE)
- [x] In game command to hot reload the plugin. (BUKKIT)
- [x] All of the above should be built with multi-module projects in mind so you can hotswap your different modules with the same test environment. (CORE)

### CODE REVIEW

**Comment by terminalsin** [comment]
> Some work (actually most of them will be in this PR) towards #122 .
> 
> Currently searching for the solution of hot reloading classes when source file changed (while not in DCEVM!). There are 2 choices I've been thinking of.
> 
> 1. When compiled jar is changed (check through .jar by hash), drag-and-drop the jar to plugins folder and unload & load the plugin.
> 2. Isolate a classloader for classes in the devtools env, and when source file changed simply recreate the classloader or have a map of changed classes stored in the class loader and make sure class loader grab the changed one, and reload the container tree.
> 
> My current approach is closer to the 2nd one, but the hard point is it will probably require a full rework to the current bootstrap system, as bootstrap are required to only accessing the plugin & fairy through reflection.
> 
> ### Framework Changes
> * [x]  Add the ability to customize the Fairy class path in the plugin (for more flexibility and so it doesn't assume you always relocated it).
> * [x]  Make sure Bukkit reload works in most cases.
> 
> ### Developer Tools
> * [x]  Ability to single line `Restarter.restart(plugin)` which restarts the plugin's lifecycle. (CORE)
> * [ ]  A source file watcher that will **hot reload** the plugin whenever it detects changes from source file (aka Build in IDE). (CORE)
> * [ ]  Built-in one-click in-game test environment (just like run-paper but better support with hotswapping). (BUKKIT)
> * [x]  When triggering a **hot reload** on a bukkit plugin, it should unload the plugin completely from bukkit and load it back. (BUKKIT)
> * [ ]  DCEVM hotswap agent should have an option to enable/disable hot reload on source file change detected. (since some hotswap changes may not necessary require a full hot reload.) (CORE)
> * [ ]  In game command to hot reload the plugin. (BUKKIT)
> * [ ]  All of the above should be built with multi-module projects in mind so you can hotswap your different modules with the same test environment. (CORE)

Changing classes in runtime is difficult due to the JVM. I'd suggest creating a Java agent. Use this as a tool: 
Agent: 
- https://github.com/HotswapProjects/HotswapAgent
- https://github.com/open-telemetry/opentelemetry-java-instrumentation
- https://github.com/brutusin/instrumentation
- https://github.com/ShiftLeftSecurity/bctrace (best)

Monitoring: https://github.com/alibaba/arthas

**Comment by LeeGodSRC** [comment]
> > Some work (actually most of them will be in this PR) towards #122 .
> > Currently searching for the solution of hot reloading classes when source file changed (while not in DCEVM!). There are 2 choices I've been thinking of.
> > 
> > 1. When compiled jar is changed (check through .jar by hash), drag-and-drop the jar to plugins folder and unload & load the plugin.
> > 2. Isolate a classloader for classes in the devtools env, and when source file changed simply recreate the classloader or have a map of changed classes stored in the class loader and make sure class loader grab the changed one, and reload the container tree.
> > 
> > My current approach is closer to the 2nd one, but the hard point is it will probably require a full rework to the current bootstrap system, as bootstrap are required to only accessing the plugin & fairy through reflection.
> > ### Framework Changes
> > 
> > * [x]   Add the ability to customize the Fairy class path in the plugin (for more flexibility and so it doesn't assume you always relocated it).
> > * [x]   Make sure Bukkit reload works in most cases.
> > 
> > ### Developer Tools
> > 
> > * [x]   Ability to single line `Restarter.restart(plugin)` which restarts the plugin's lifecycle. (CORE)
> > * [ ]   A source file watcher that will **hot reload** the plugin whenever it detects changes from source file (aka Build in IDE). (CORE)
> > * [ ]   Built-in one-click in-game test environment (just like run-paper but better support with hotswapping). (BUKKIT)
> > * [x]   When triggering a **hot reload** on a bukkit plugin, it should unload the plugin completely from bukkit and load it back. (BUKKIT)
> > * [ ]   DCEVM hotswap agent should have an option to enable/disable hot reload on source file change detected. (since some hotswap changes may not necessary require a full hot reload.) (CORE)
> > * [ ]   In game command to hot reload the plugin. (BUKKIT)
> > * [ ]   All of the above should be built with multi-module projects in mind so you can hotswap your different modules with the same test environment. (CORE)
> 
> Changing classes in runtime is difficult due to the JVM. I'd suggest creating a Java agent. Use this as a tool: Agent:
> 
> * https://github.com/HotswapProjects/HotswapAgent
> * https://github.com/open-telemetry/opentelemetry-java-instrumentation
> * https://github.com/brutusin/instrumentation
> * https://github.com/ShiftLeftSecurity/bctrace (best)
> 
> Monitoring: https://github.com/alibaba/arthas

thanks for your information, but I'm not exactly trying to do what hotswap agent does. I'm trying to achieve hot reloading to the "plugin", which is the projects that built on top of fairy. where when source file changed detected, you won't need to reboot the entire server and fairy itself, instead, it shutdown the plugin, resets the classloader, and boot backup.
Kinda like what spring boot devtool does.

**Review by terminalsin — CHANGES_REQUESTED** [review]
Lot more unit tests should be made:

- [x] Testing plugin init order (load, init, disinit)
- [x] Testing plugin init duplicates
- [x] Testing container load order
- [x] Testing container init and load duplicates (has happened before)
- [x] Testing lifecycle calls
- [x] Testing event listening
- [x] Testing if commands are duplicated or properly unloaded
- [x] Testing if lifecycle objects still alive (aka still registered to some functions etc)

**Comment by LeeGodSRC** [comment]
> Lot more unit tests should be made:
> 
> * Testing plugin init order (load, init, disinit)
> * Testing plugin init duplicates
> * Testing container load order
> * Testing container init and load duplicates (has happened before)
> * Testing lifecycle calls
> * Testing event listening
> * Testing if commands are duplicated or properly unloaded
> * Testing if lifecycle objects still alive (aka still registered to some functions etc)

Some tests should already be covered:
- Testing container load order
- Testing lifecycle calls
- Testing if lifecycle objects still alive (aka still registered to some functions etc)
https://github.com/LeeGodSRC/fairy/blob/feat/devtools/io.fairyproject.platforms/core-platform/src/test/java/io/fairyproject/container/ContainerIntegrationTest.java

- Testing event listening
https://github.com/LeeGodSRC/fairy/tree/feat/devtools/io.fairyproject.platforms/core-platform/src/test/java/io/fairytest/event

**Review by terminalsin — APPROVED** [review]
Good changes and improvements, LGTM

**Comment by LeeGodSRC** [comment]
Closed to merge in #128

**Pull request closed without merging**
